CHANGELOG.md

**Contributions**: We are not currently taking public contributions - see our [contributions](https://docs.improbable.io/unity/alpha/contributing) policy. However, we are accepting issues and we do want your [feedback](https://github.com/spatialos/gdk-for-unity#give-us-feedback).
-------
Describe your changes here.
How did you test these changes prior to submitting this pull request?
What automated tests are included in this PR?

Adding a changelog

---

CHANGELOG.md

Semantic merge conflicts are sad - fixing duplicate entry

Remove Duplicate Entry from Changelog

---

CHANGELOG.md
cloud_launch.json
default_launch.json
spatialos.json
workers/unity/spatialos.UnityGameLogic.worker.json

Update launch configurations to use the new Runtime.
ran locally + in cloud
n/a
**Did you remember a changelog entry?**
I have now

Use the new Runtime by default

---

ci/build.sh
ci/upload-launch.sh

- Updated the build script to use the shared generic build script + build mobile clients.
- Added a launch deployment script for use in Release QA.
Will run the TC builds.
Release process change incoming.
**Did you remember a changelog entry?**
N/A

Update Build Script + Add Launch Script

---

cloud_launch.json
default_launch.json

Remove the transitional template, as the new runtime is now the default runtime.
`spatial local launch`
None
@zeroZshadow

Remove the transitional template, as the new runtime is now the default runtime.

---

workers/unity/Assets/link.xml
workers/unity/Assets/link.xml.meta

This fixes UTY-1800 and prevents unwanted stripping of core classes.
Ran an iOSClient on an iPad
n/a
@oblm

Add link.xml

---

.buildkite/premerge.steps.yaml
.buildkite/release-qa.steps.yaml

Looks like we forgot to change them both.

Bump BK queue ID

---

.buildkite/premerge.steps.yaml
.buildkite/release-qa.steps.yaml
workers/unity/Packages/manifest.json
workers/unity/ProjectSettings/ProjectVersion.txt

Changes from the upgrade - will update with a new BK agent queue when that's done.

Unity 2018.3.11 Upgrade

---

.buildkite/hooks/post-checkout
.buildkite/premerge.steps.yaml
.buildkite/release-qa.steps.yaml
ci/bootstrap.sh

Fix Buildkite

---

.buildkite/premerge.steps.yaml
.buildkite/release-qa.steps.yaml

Its that time of day - this queue has more logs being forwarded to Kibana for better debug + tracking.

BK new queue

---

workers/unity/ProjectSettings/ProjectSettings.asset

disabled reactive components

---

ci/launch.sh

Stop locking due to `spatial` + NPM package upgrade

Fix launch script

---

README.md

This got missed in the last release. Simple instructions now!

Remove outdated readme

---

.buildkite/premerge.steps.yaml

The bug that affected this should have been fixed in 2019.1.8f1 or something like that

Re-enable IL2CPP builds

---

.buildkite/premerge.steps.yaml
.buildkite/release-qa.steps.yaml

Update buildkite queue

---

CHANGELOG.md
gdk.pinned
workers/unity/Assets/BlankProject/Scripts/Config/EntityTemplates.cs

- update blank project with breaking change from https://github.com/spatialos/gdk-for-unity/pull/1315

Pass EntityId into Player EntityTemplate method

---

ci/bootstrap.sh
ci/get-shared-ci.sh
ci/launch.sh
ci/lint.sh
ci/shared-ci.pinned

As per the guide in https://improbableio.atlassian.net/browse/UTY-2600

New Buildkite instrumentation format

---

.buildkite/premerge.steps.yaml

Update queue to v4-20-07-06-120608-bk13080-eb89af6c. [Bake Link] (https://buildkite.com/improbable/platform-bakery/builds/13080)
Premerge build
**Did you remember a changelog entry?**

UTY-2607: Update linux queue

---

.buildkite/premerge.steps.yaml
.buildkite/release-qa.steps.yaml
CHANGELOG.md
ci/launch.sh

For [UTY-2588](https://improbableio.atlassian.net/browse/UTY-2588)
- Changed all occurrences of `\\` to a single `/` in the artifact paths
How did you test these changes prior to submitting this pull request?
Checked build was successful on buildkite
N/A

Update buildkite artifact path to only use forward slash

---

.buildkite/premerge.steps.yaml
.buildkite/release-qa.steps.yaml

set max ci agents to 12
How did you test these changes prior to submitting this pull request?
What automated tests are included in this PR?
**Did you remember a changelog entry?**

UTY-2657: set max instances to 12 for windwos, linux and mac

---

workers/unity/Assets/BlankProject/Scripts/Config/EntityTemplates.cs

- add position/coords variable to player entity template, used in the blank project tutorial
n/a
n/a

Add variable for position/coords when creating Player entity template
